# Generated by Django 5.0 on 2024-10-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresult',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
