# Generated by Django 5.0 on 2024-10-02 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('voter_intimidation', 'Voter Intimidation'), ('machine_malfunction', 'Voting Machine Malfunction'), ('long_wait_times', 'Long Wait Times'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='incident_evidence/')),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
