# Generated by Django 5.0 on 2024-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_electionresult_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionresult',
            name='total_votes',
        ),
        migrations.AddField(
            model_name='electionresult',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('senator', 'Senator'), ('mp', 'Member of Parliament'), ('mca', 'Member of County Assembly')], default=0.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='registered_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
